### ISSUE TITLE
`ArithmeticException` when computing the delta coverage

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/code-coverage-api-plugin#413]
### Jenkins and plugins versions report

With the new plugin versions our build jobs fail. See actual results.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins 2.346.1 LTS with Code Coverage API 3.0.0

### Reproduction steps

Run for a branch with jacoco and istanbul coverage files analyzed with the following command
```
      publishCoverage(
          sourceFileResolver: sourceFiles('NEVER_STORE'),
          calculateDiffForChangeRequests: true,
          adapters: [
              jacocoAdapter(
                  mergeToOneReport: true,
                  path: '**/target/site/jacoco-ut/jacoco.xml,**/target/site/jacoco-it/jacoco.xml'),
              istanbulCoberturaAdapter('**/target/coverage-reports/cobertura-coverage.xml')])
```

### Expected Results

Everything works.

### Actual Results

The coverage results are shown, but the job crashes with the following exceptions
```
13:37:51  [Coverage] [-ERROR-] Errors while reporting code coverage results:
13:37:51  [Coverage] [-ERROR-] Computing delta information failed with an exception:
13:37:51  [Coverage] [-ERROR-] org.eclipse.jgit.errors.MissingObjectException: Missing unknown b0bf240636ead93d427d344f994de2b36a4f64bd
13:37:51  [Coverage] [-ERROR-] 	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135)
13:37:51  [Coverage] [-ERROR-] 	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:212)
13:37:51  [Coverage] [-ERROR-] 	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1068)
13:37:51  [Coverage] [-ERROR-] 	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:978)
13:37:51  [Coverage] [-ERROR-] 	at io.jenkins.plugins.forensics.git.delta.DeltaRepositoryCallback.calculateDelta(DeltaRepositoryCallback.java:86)
13:37:51  [Coverage] [-ERROR-] 	at io.jenkins.plugins.forensics.git.delta.DeltaRepositoryCallback.invoke(DeltaRepositoryCallback.java:70)
13:37:51  [Coverage] [-ERROR-] 	at io.jenkins.plugins.forensics.git.delta.DeltaRepositoryCallback.invoke(DeltaRepositoryCallback.java:41)
13:37:51  [Coverage] [-ERROR-] 	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
13:37:51  [Coverage] [-ERROR-] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:84)
13:37:51  [Coverage] [-ERROR-] 	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
13:37:51  [Coverage] [-ERROR-] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
13:37:51  [Coverage] [-ERROR-] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:902)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:854)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.Request$2.run(Request.java:376)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
13:37:51  [Coverage] [-ERROR-] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
13:37:51  [Coverage] [-ERROR-] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
13:37:51  [Coverage] [-ERROR-] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
13:37:51  [Coverage] [-ERROR-] 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
13:37:51  [Coverage] [-ERROR-] 	at java.base/java.lang.Thread.run(Unknown Source)
13:37:51  [Coverage] Calculating the code delta...
13:37:51  [Coverage] -> Git delta calculator successfully created in working tree '/home/jenkins/agent/workspace/xxx'
```

```
 java.lang.ArithmeticException: overflow: mul
13:38:03  	at org.apache.commons.lang3.math.Fraction.mulAndCheck(Fraction.java:636)
13:38:03  	at org.apache.commons.lang3.math.Fraction.multiplyBy(Fraction.java:788)
13:38:03  	at io.jenkins.plugins.coverage.model.CoveragePercentage.valueOf(CoveragePercentage.java:31)
13:38:03  	at io.jenkins.plugins.coverage.model.CoverageNode.lambda$computeDeltaAsPercentage$8(CoverageNode.java:387)
13:38:03  	at one.util.streamex.AbstractStreamEx.lambda$toMapThrowing$0(AbstractStreamEx.java:94)
13:38:03  	at java.base/java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:2962)
13:38:03  	at one.util.streamex.AbstractStreamEx.forEach(AbstractStreamEx.java:352)
13:38:03  	at one.util.streamex.AbstractStreamEx.toMapThrowing(AbstractStreamEx.java:94)
13:38:03  	at one.util.streamex.StreamEx.toSortedMap(StreamEx.java:1179)
13:38:03  	at io.jenkins.plugins.coverage.model.CoverageNode.computeDeltaAsPercentage(CoverageNode.java:387)
13:38:03  	at io.jenkins.plugins.coverage.model.CoverageReporter.run(CoverageReporter.java:128)
13:38:03  	at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:133)
13:38:03  	at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:114)
13:38:03  	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
13:38:03  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
13:38:03  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
13:38:03  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:38:03  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
13:38:03  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13:38:03  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
13:38:03  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
13:38:03  	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by uhafner** [comment]
The second exception is shown in the log only (and does not break the build). Can you file an issue in the git-forensics plugin?
