### ISSUE TITLE
java.lang.ArithmeticException: overflow: mul

### ISSUE THREAD

**Issue by mikkhola** [jenkinsci/code-coverage-api-plugin#637]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Code Coverage API Version 4.0.2
Jenkins Version 2.387.1
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Unfortunately, I wasn't able to reproduce this issue with a basic test environment. The Code Coverage step fails sporadically in java.lang.ArithmeticException both with Jacoco and Cobertura reports. I will update this issue when I'm able to reproduce this properly.

### Expected Results

The plugin should produce code coverage reports properly.

### Actual Results

Build fails to this kind of exception:
```
java.lang.ArithmeticException: overflow: mul
	at org.apache.commons.lang3.math.Fraction.mulAndCheck(Fraction.java:636)
	at org.apache.commons.lang3.math.Fraction.multiplyBy(Fraction.java:788)
	at io.jenkins.plugins.coverage.metrics.model.ElementFormatter.formatDelta(ElementFormatter.java:350)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageBuildAction.formatDelta(CoverageBuildAction.java:475)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageChecksPublisher.format(CoverageChecksPublisher.java:119)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageChecksPublisher.lambda$getChecksTitle$1(CoverageChecksPublisher.java:103)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageChecksPublisher.getChecksTitle(CoverageChecksPublisher.java:104)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageChecksPublisher.extractChecksDetails(CoverageChecksPublisher.java:85)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageChecksPublisher.publishCoverageReport(CoverageChecksPublisher.java:79)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageRecorder.perform(CoverageRecorder.java:400)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageRecorder.perform(CoverageRecorder.java:379)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageStep$Execution.run(CoverageStep.java:347)
	at io.jenkins.plugins.coverage.metrics.steps.CoverageStep$Execution.run(CoverageStep.java:316)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`
```

**Comment by mikkhola** [comment]
Thanks for the super fast fix!
